# Generated by Django 3.2.9 on 2021-11-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermLexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500, unique=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indexer.document')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indexer.termlexicon')),
            ],
        ),
    ]
