# Generated by Django 3.2.9 on 2021-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
